name: asyltas_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.1.11
  carousel_slider: ^5.0.0
  mask_text_input_formatter: ^2.4.0
  provider: ^6.1.2
  flutter_staggered_grid_view: ^0.6.1
  flutter_dynamic_staggered_grid_view: ^1.0.0
  cached_network_image: ^3.4.0
  intl: ^0.18.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  cloud_firestore: ^5.1.0
  firebase_core: ^3.2.0
  shared_preferences: ^2.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.5
  json_serializable: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Gilroy
      fonts:
        - asset: fonts/gilroy/Gilroy-Black.ttf
          weight: 900
        - asset: fonts/gilroy/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: fonts/gilroy/Gilroy-Bold.ttf
          weight: 700
        - asset: fonts/gilroy/Gilroy-SemiBold.ttf
          weight: 600
        - asset: fonts/gilroy/Gilroy-Medium.ttf
          weight: 500
        - asset: fonts/gilroy/Gilroy-Regular.ttf
          weight: 400
        - asset: fonts/gilroy/Gilroy-Light.ttf
          weight: 300
        - asset: fonts/gilroy/Gilroy-UltraLight.ttf
          weight: 200
        - asset: fonts/gilroy/Gilroy-Thin.ttf
          weight: 100
